# Generated by Django 6.0.6 on 2026-07-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
