# Generated by Django 6.0.6 on 2026-07-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Bills', 'Bills'), ('Education', 'Education'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Transport', 'Transport'), ('Others', 'Others')], default='others', max_length=20),
        ),
    ]
